### ISSUE TITLE
部分bug反馈

### ISSUE THREAD

**Issue by Jasonzhu1207** [icylian/MDPings#2]
测试环境：Harmony OS 4.0 ［Android12（API31）］
app版本：1.0.0

1.无法连接哪吒面板，不论是填ip还是域名还是http或https，始终提示Couldn't connect to the server, please check your internet connection.同样的域名和密钥nezha bot可以正常访问，app不论走代理还是大陆直连都无法连接

2.开屏启动页相当难看，黑底上放一个带着大白边的icon还是直角边![Screenshot_20241121_195158_com.sekusarisu.mdpings.jpg](https://github.com/user-attachments/assets/161681c9-00bb-4d59-84dc-5e2a6f90891c)

3.小窗或滑到后台在切回来几乎100%未响应

**Comment by icylian** [comment]
域名格式是https://www.example.com/
请先尝试加上后面的斜杠。启动页暂时没有鸿蒙设备进行测试，后续会调整开屏的ui

**Comment by Jasonzhu1207** [comment]
> 域名格式是https://www.example.com/
> 请先尝试加上后面的斜杠。启动页暂时没有鸿蒙设备进行测试，后续会调整开屏的ui

加斜杠可以了，感谢
另外希望设置里加一个 黑夜/日间/自动 的手动选择开关

**Comment by icylian** [comment]
黑夜/日间计划会跟主题设置功能一起更新
