### ISSUE TITLE
【建议】添加实例问题

### ISSUE THREAD

**Issue by suchenqaq** [icylian/MDPings#5]
"https://your.nezha.api.com/" 这个编辑框提示小白很容易被误导 建议改成“面板首页地址“ API BACKEND 改成“面板地址“

**Comment by icylian** [comment]
下个版本修复，统一语言的时候漏掉了这里的语言资源没改

**Comment by icylian** [comment]
v1版本已修复，v0版本等我v1搞烦了顺手补上，先close了
