### ISSUE TITLE
【问题反馈】1.0.4还是有Toast不明错误

### ISSUE THREAD

**Issue by WangQi107** [icylian/MDPings#6]
![QQ20241205-094945](https://github.com/user-attachments/assets/294be44b-1479-46b4-a435-ce1002d63efd)
api后面斜杠添加了，1.0.0版本正常使用，更新、重装都是一样的，dashboard版本0.20.13
用postman调试是正常的，看logcat应该是http的问题

**Comment by icylian** [comment]
是http的问题，Android 9以及更高版本的系统默认不允许http明文连接，你的环境是用不了https吗？面板没ssl感觉还挺危险的。

**Comment by WangQi107** [comment]
> 是http的问题，Android 9以及更高版本的系统默认不允许http明文连接，你的环境是用不了https吗？面板没ssl感觉还挺危险的。

我知道，我用的还是v0，没用ssl。

**Comment by WangQi107** [comment]
后续会加HTTP支持吗？

**Comment by icylian** [comment]
如果能找到比较优雅的支持方式会加上，如果没找到到时候我单独打个包给你吧，反正v0版本比较稳定，不会有什么重大更新了

**Comment by WangQi107** [comment]
> 如果能找到比较优雅的支持方式会加上，如果没找到到时候我单独打个包给你吧，反正v0版本比较稳定，不会有什么重大更新了

步骤一
在main / res 目录下创建一个xml 文件夹， 然后在改文件夹中创建一个
network_security_config.xml 文件
该文件中的配置如下

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>

步骤二
在AndroidManifest.xml文件中 application 配置中添加 android:networkSecurityConfig=“@xml/network_security_config”
代码如下

<application
        android:label="flutter_video_detail"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config"
       >
以上操作就可以了就可以了

**Comment by WangQi107** [comment]
xml/network_security_config.xml文件中添加
![image](https://github.com/user-attachments/assets/da052c95-50d7-4258-a7d1-1868d66a92fc)
就可以了，你现在的这个文件里只添加了域名白名单
![image](https://github.com/user-attachments/assets/393e0417-a84c-413c-924e-bf8c05d57c4a)
打包就不麻烦你了，我已经测试过可以用了。

**Comment by icylian** [comment]
ok，我是只放行了ipapi那边的ip信息查询，你能打包那我就关了。
